spring:
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,refresh

global:
  params:
    p1: 0000
    p2: 1111
