spring:
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id: r2
          uri: "http://localhost:8082"
          predicates:
            - Path=/products/**
