spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:h2:mem:billings-db
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  h2:
    console:
      enabled: true
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: *
