spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:h2:mem:bills-db
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8083
