spring:
  application:
    name: config-service
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Abderaoufsouissi/config-repo
server:
  port: 9999
